% Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
% By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not exceed four million,
% find the sum of the even-valued terms.

tic
fibo = [1 2]; % Establishes the first two terms of the Fibonacci sequence

i = 2;
answer = 2; % The second term that was established, 2, is itself even. So we initialize answer to be 2. 

while fibo(i) < 4e6
    i = i + 1; % Incrementing by one to find the next Fibonacci number
    
    fibo(i) = fibo(i - 1) + fibo(i - 2); % Calculating the next Fibonacci number.
                                         % Matlab will store this as the
                                         % newest element in the growing
                                         % row vector "fibo". That is, 
                                         % its length will increase by 1
                                         % during each iteration of the
                                         % while loop. Note: it's a Matlab convention
                                         % to create a new cell with the newly 
                                         % designated entry where there
                                         % wasn't one for an already
                                         % existing vector/matrix.
    if mod(fibo(i), 2) == 0
        answer = answer + fibo(i);
    end
end

disp(answer)
toc